# Used for generalizing GCIQL to novel dynamics
agent_name: gciql
discrete: ${env.discrete}

# Dataset hyperparameters.
dataset_class: GCDataset  # Dataset class name.
value_p_curgoal: 0.2  # Probability of using the current state as the value goal.
value_p_trajgoal: 0.8  # Probability of using a future state in the same trajectory as the value goal.
value_p_randomgoal: 0.0  # Probability of using a random state as the value goal.
value_geom_sample: True  # Whether to use geometric sampling for future value goals.
actor_p_curgoal: 0.0  # Probability of using the current state as the actor goal.
actor_p_trajgoal: 1.0  # Probability of using a future state in the same trajectory as the actor goal.
actor_p_randomgoal: 0.0  # Probability of using a random state as the actor goal.
actor_geom_sample: False  # Whether to use geometric sampling for future actor goals.
gc_negative: True  # Whether to use '0 if s : :  g else -1' (True) or '1 if s : :  g else 0' (False) as reward.
p_aug: 0.0  # Probability of applying image augmentation.
frame_stack: null  # Number of frames to stack.
